# Citable power statement ------------------------------------------------------

describe_dgp <- function(d) {
  is_panel <- identical(d$route, "panel")
  ## panel variables carry their within-unit persistence (icc), in the
  ## constructor's order: focal, moderator, covariates
  pvars <- c(list(d$focal), if (!is.null(d$moderator)) list(d$moderator),
             if (is.list(d$covariates)) d$covariates)
  icc_of <- function(v) {
    if (!is_panel) return(NULL)
    i <- match(v$name, vapply(pvars, function(p) p$name, character(1)))
    if (is.na(i) || is.null(d$iccs)) NULL else d$iccs[i]
  }
  var_desc <- function(v) {
    base <- if (v$type == "binary") sprintf("binary, prevalence %.2f", v$p)
            else sprintf("continuous, mean %.3g, SD %.3g", v$mean, v$sd)
    icc <- icc_of(v)
    if (!is.null(icc)) {
      base <- paste0(base, if (icc >= 1) ", time-constant"
                           else if (icc <= 0) ", redrawn each period"
                           else sprintf(", within-unit persistence (icc) %.2f", icc))
    }
    sprintf("%s (%s)", v$name, base)
  }
  ## the latent (Gaussian-copula) dependence that was specified, if any
  dep_desc <- function(over) {
    r <- d$spec$correlation
    if (is.null(r)) return(NULL)
    off <- if (is.matrix(r)) r[upper.tri(r)] else r
    if (!length(off) || all(abs(off) < 1e-12)) return(NULL)
    lvl <- if (is_panel) ", at both the unit and the within-unit level" else ""
    if (is.matrix(r)) {
      sprintf(paste0("a latent (Gaussian-copula) correlation matrix over %s ",
                     "with off-diagonal entries from %.2f to %.2f%s"),
              over, min(off), max(off), lvl)
    } else {
      sprintf("an exchangeable latent (Gaussian-copula) correlation of %.2f among %s%s",
              r, over, lvl)
    }
  }
  parts <- if (is_panel) {
    sprintf(paste0("a correlated random effects %s model over %s periods per ",
                   "unit (latent unit-effect share rho = %.2f, %.0f%% of it ",
                   "loaded on regressor means), estimated by pooled %s with ",
                   "Mundlak means%s and unit-clustered standard errors, with ",
                   "focal variable %s"),
            d$model, panel_len_label(d), d$rho, 100 * d$cre_share, d$model,
            if (isTRUE(d$unbalanced))
              " over observed periods plus period-count cohort indicators (Wooldridge, 2019)"
            else "",
            var_desc(d$focal))
  } else if (identical(d$route, "iv")) {
    sprintf(paste0("a probit model with an endogenous focal variable %s ",
                   "(error correlation %.2f with the first stage), ",
                   "instrumented by %s (%s first stage, instrument strength ",
                   "%.2f as a share of the focal's %svariance) and estimated ",
                   "by control-function probit with stacked ",
                   "method-of-moments robust standard errors (the estimator ",
                   "of Stata's cfprobit)"),
            var_desc(d$focal), d$endogeneity,
            paste(vapply(d$instruments, var_desc, character(1)),
                  collapse = ", "),
            d$first_stage, d$iv_strength,
            if (d$focal$type == "binary") "latent " else "")
  } else {
    sprintf("a %s model with focal variable %s", d$model, var_desc(d$focal))
  }
  if (!is.null(d$moderator))
    parts <- paste0(parts,
                    sprintf(", moderator %s, and their interaction",
                            var_desc(d$moderator)))
  covs <- if (identical(d$builder, "from_fit")) {
    sprintf(paste0("covariate rows and nuisance coefficients taken from a ",
                   "fitted pilot model (%s; %d pilot observations, ",
                   "resampled with replacement, the focal jointly with them)"),
            d$formula_str, d$n_emp)
  } else if (d$route == "empirical") {
    foc <- if (!is.null(d$emp_xd)) "the focal resampled jointly with the pilot rows"
           else "the focal drawn independently of the resampled rows"
    if (d$k > 0L) {
      sprintf("covariates resampled with replacement from %d pilot observations (%s), %s",
              d$n_emp, paste(d$covariates, collapse = ", "), foc)
    } else {
      sprintf("no covariates, %s (%d pilot observations)", foc, d$n_emp)
    }
  } else {
    ## parametric, panel, and IV routes: named marginals, then the latent
    ## dependence actually specified (the IV focal is generated by its first
    ## stage, so there the dependence runs over the exogenous block)
    is_iv <- identical(d$route, "iv")
    blk <- c(if (!is_iv) "the focal variable",
             if (!is.null(d$moderator)) "the moderator",
             if (d$k > 0L) "the covariates",
             if (is_iv) "the instruments")
    n_vars <- (!is_iv) + (!is.null(d$moderator)) + d$k +
      (if (is_iv) length(d$instruments) else 0L)
    over <- if (length(blk) > 1L) {
      paste(paste(blk[-length(blk)], collapse = ", "), "and", blk[length(blk)])
    } else blk
    dep <- if (n_vars > 1L) dep_desc(over) else NULL
    cv <- if (d$k > 0L) {
      sprintf("parametric covariates %s",
              paste(vapply(d$covariates, var_desc, character(1)),
                    collapse = ", "))
    } else "no additional covariates"
    paste0(cv,
           if (!is.null(dep)) paste0(", with ", dep)
           else if (n_vars > 1L) paste0(", with ", over, " mutually independent")
           else "")
  }
  sprintf(paste0("%s; %s; baseline outcome rate %.3f with the focal%s at ",
                 "reference; nuisance covariates contribute a latent ",
                 "pseudo-R-squared of %.2f"),
          parts, covs, d$baseline,
          if (is.null(d$moderator)) "" else " and moderator",
          d$signal_implied)
}

claim_text <- function(claim, sesoi, conf, rule = FALSE) {
  cl <- sprintf("%s%%", format(round(100 * conf, 2)))
  ## the claim's own error rate follows from its interval: two-sided for
  ## detection, one-sided (and TOST) for the SESOI claims
  al <- if (identical(claim, "detect")) 1 - conf else (1 - conf) / 2
  al_txt <- sprintf("%g%%", round(100 * al, 3))
  by_n <- if (isTRUE(rule)) ", set as a function of the sample size" else ""
  switch(claim,
    minimum = sprintf(paste0("the minimum-effect claim (the %s confidence ",
                             "interval's lower bound exceeding the smallest ",
                             "effect size of interest, %.3f; a one-sided ",
                             "test at alpha = %s%s)"), cl, sesoi, al_txt, by_n),
    detect = sprintf(paste0("the detection claim (the %s confidence interval ",
                            "excluding zero in the hypothesized direction; a ",
                            "two-sided test at alpha = %s%s)"), cl, al_txt, by_n),
    equivalence = sprintf(paste0("the equivalence claim (the %s confidence ",
                                 "interval lying within +/-%.3f; two ",
                                 "one-sided tests at alpha = %s%s)"),
                          cl, sesoi, al_txt, by_n))
}

#' Render a power analysis as a citable methods paragraph
#'
#' Turns a [ape_power()], [ape_n()], or [ape_mde()] result into a
#' self-contained methods paragraph stating the estimand, the full
#' data-generating assumptions, the claim and CI convention (including a
#' sample-size rule for `alpha` when one was used), and the Monte Carlo
#' precision -- the transparency artifact for grant applications and
#' preregistrations. For an [ape_alpha()] result the paragraph states the
#' justification of the error rate instead: the objective and its
#' weights, the chosen level and its flat range, the cap, and the
#' realized-size verification when it was run.
#'
#' @param x A `powerape_power`, `powerape_n`, `powerape_mde`, or
#'   `powerape_alpha` object.
#' @return A character string of class `powerape_statement` (printed
#'   wrapped).
#' @examples
#' \donttest{
#' d <- ape_dgp(focal = pa_var("treat", "binary", p = 0.5), baseline = 0.30)
#' d <- set_ape(d, target = 0.10)
#' pw <- ape_power(d, n = 800, claim = "minimum", sesoi = 0.03,
#'                 nsim = 500, seed = 1)
#' power_statement(pw)
#' }
#' @export
power_statement <- function(x) {
  stopifnot(inherits(x, "powerape_power") || inherits(x, "powerape_n") ||
              inherits(x, "powerape_mde") || inherits(x, "powerape_alpha"))
  if (inherits(x, "powerape_alpha")) return(alpha_statement(x))
  rule <- !is.null(x$alpha_rule)
  d <- x$dgp
  is_aie <- identical(x$estimand, "aie")
  est_long <- if (is_aie) "average interaction effect (AIE)" else "average partial effect (APE)"
  est_short <- if (is_aie) "AIE" else "APE"
  subject <- if (is_aie) sprintf("%s-by-%s", d$focal$name, d$moderator$name) else d$focal$name

  s1 <- sprintf(paste0("We conducted a simulation-based power analysis for the ",
                       "%s of %s using the powerape package (version %s), ",
                       "following the confidence-interval approach of ",
                       "Riesthuis (2024)."),
                est_long, subject, as.character(packageVersion("powerape")))
  s2 <- sprintf("The assumed data-generating process was %s.", describe_dgp(d))
  s3 <- if (inherits(x, "powerape_mde")) {
    NULL
  } else {
    sprintf("The assumed true %s was %.3f (%.1f percentage points)%s.",
            est_short, x$target, 100 * x$target,
            if (is_aie) sprintf(paste0(", with conditional-at-reference ",
                                       "main-effect APEs of %.3f (%s) and ",
                                       "%.3f (%s)"),
                                d$main_focal, d$focal$name,
                                d$main_moderator, d$moderator$name)
            else "")
  }
  is_panel <- identical(d$route, "panel")
  n_text <- if (is_panel) {
    sprintf("n = %d units observed over %s periods (%s unit-period observations)",
            x$n, panel_len_label(d), panel_obs_label(d, x$n))
  } else {
    sprintf("n = %d", x$n)
  }
  s4 <- if (inherits(x, "powerape_mde")) {
    conf_frag <- if (isTRUE(x$confirmed)) {
      sprintf(paste0(", confirmed by a high-precision verification run ",
                     "(simulated power %.3f, Monte Carlo SE %.3f, %d ",
                     "replications)"),
              x$power, x$mcse, x$nsim_confirm)
    } else {
      sprintf(" (simulated power %.3f, Monte Carlo SE %.3f)", x$power, x$mcse)
    }
    if (isTRUE(x$is_margin)) {
      sprintf(paste0("At a sample size of %s, the tightest equivalence ",
                     "bounds establishable with %.0f%% power were +/-%.3f ",
                     "(%.1f percentage points)%s."),
              n_text, 100 * x$goal, x$mde, 100 * x$mde, conf_frag)
    } else {
      sprintf(paste0("At a sample size of %s, the minimum detectable %s at ",
                     "%.0f%% power for %s was %.3f (%s of %.1f percentage ",
                     "points)%s."),
              n_text, est_short, 100 * x$goal,
              claim_text(x$claim, x$sesoi, x$conf, rule), x$mde,
              if (x$mde < 0) "a decrease" else "an increase",
              100 * abs(x$mde), conf_frag)
    }
  } else if (inherits(x, "powerape_n")) {
    size_noun <- if (is_panel) "number of units" else "total sample size"
    if (isTRUE(x$confirmed)) {
      sprintf(paste0("The required %s for %.0f%% power for %s ",
                     "was %s, confirmed by a high-precision verification ",
                     "run (simulated power %.3f, Monte Carlo SE %.3f, %d ",
                     "replications)."),
              size_noun, 100 * x$goal, claim_text(x$claim, x$sesoi, x$conf, rule),
              n_text, x$power, x$mcse, x$nsim_confirm)
    } else {
      sprintf(paste0("The required %s for %.0f%% power for %s ",
                     "was %s (simulated power %.3f, Monte Carlo SE %.3f, ",
                     "%d replications per search step)."),
              size_noun, 100 * x$goal, claim_text(x$claim, x$sesoi, x$conf, rule),
              n_text, x$power, x$mcse, x$nsim)
    }
  } else {
    sprintf(paste0("At a sample size of %s, simulated power for %s ",
                   "was %.3f (Monte Carlo SE %.3f; %d replications)."),
            n_text, claim_text(x$claim, x$sesoi, x$conf, rule), x$power, x$mcse,
            x$nsim)
  }
  s5 <- if (inherits(x, "powerape_power") && !is.null(x$sesoi)) {
    o <- x$outcomes
    sprintf(paste0("Across replications, the probability of concluding a ",
                   "meaningful effect was %.3f, of detection without ",
                   "meaningfulness %.3f, of an inconclusive result %.3f, ",
                   "and of equivalence %.3f."),
            o[["minimum"]], o[["detect_only"]], o[["inconclusive"]],
            o[["equivalence"]])
  } else {
    NULL
  }
  est_desc <- if (identical(d$route, "iv")) {
    paste0("two-step control-function estimation with stacked ",
           "method-of-moments robust standard errors and delta-method ",
           "Wald confidence intervals")
  } else if (identical(x$se %||% "model", "robust")) {
    paste0("maximum likelihood with heteroskedasticity-robust (sandwich) ",
           "standard errors and delta-method Wald confidence intervals")
  } else {
    "maximum likelihood with delta-method Wald confidence intervals"
  }
  ## how replications without a usable estimate were scored: failed fits
  ## always count against the claim; separation (an identifying cell with
  ## no events or no non-events, where the ML effect does not exist) counts
  ## as failed by default and is kept under separation = "keep"
  keep <- identical(x$separation, "keep")
  sepd <- x$separated %||% 0
  cell <- if (is_aie) "focal-by-moderator cell" else "focal cell"
  s6 <- if (inherits(x, "powerape_power")) {
    other <- x$outcomes[["failed"]] - (if (keep) 0 else sepd)
    if (keep) {
      sprintf(paste0("Estimation used %s; replications whose model fit ",
                     "failed (%.1f%%) counted against the claim, and ",
                     "replications with separation (a %s with no events ",
                     "or no non-events; %.1f%%) were retained with their Wald ",
                     "intervals."),
              est_desc, 100 * other, cell, 100 * sepd)
    } else {
      sprintf(paste0("Estimation used %s; replications without a ",
                     "maximum-likelihood estimate, from a failed fit or from ",
                     "separation (a %s with no events or no non-events), ",
                     "counted against the claim (%.1f%% of replications%s)."),
              est_desc, cell, 100 * x$outcomes[["failed"]],
              if (sepd > 0) sprintf(", %.1f%% with separation", 100 * sepd) else "")
    }
  } else {
    sprintf(paste0("Estimation used %s; replications without a ",
                   "maximum-likelihood estimate (failed fits%s) counted ",
                   "against the claim%s."),
            est_desc,
            if (keep) "" else sprintf(" and separation, a %s with no events or no non-events", cell),
            if (keep) ", while replications with separation were retained with their Wald intervals" else "")
  }

  structure(paste(c(s1, s2, s3, s4, s5, s6), collapse = " "),
            class = "powerape_statement")
}

#' @export
print.powerape_statement <- function(x, ...) {
  cat(strwrap(unclass(x), width = 78), sep = "\n")
  invisible(x)
}
